export const QUESTION_CATEGORY_CATALOG = [
  { code: 'THU_TUC_HAI_QUAN', name: 'Thủ tục và khai báo hải quan' },
  { code: 'HS_PHAN_LOAI', name: 'HS và phân loại hàng hóa' },
  { code: 'THUE_TRI_GIA', name: 'Thuế và trị giá hải quan' },
  { code: 'XUAT_XU_CHUNG_TU', name: 'Xuất xứ và chứng từ' },
  { code: 'CHINH_SACH_CHUYEN_NGANH', name: 'Chính sách mặt hàng và chuyên ngành' },
  { code: 'DNCX_XNK_TAI_CHO', name: 'DNCX và XNK tại chỗ' },
  { code: 'GIA_CONG_SXXK', name: 'Gia công và SXXK' },
  { code: 'LOAI_HINH_DAC_THU', name: 'Loại hình và xử lý đặc thù' },
  { code: 'PHAP_LY_TUAN_THU', name: 'Pháp lý, tuân thủ và xử phạt' },
  { code: 'LOGISTICS_VAN_TAI', name: 'Logistics, vận tải và hiện trường' },
  { code: 'VAN_HANH_CS_CHAT_LUONG', name: 'Vận hành CS và chất lượng' },
  { code: 'AN_TOAN_KY_THUAT', name: 'An toàn và kiểm tra kỹ thuật' },
] as const;

const TOPICS_BY_CATEGORY: Record<string, string[]> = {
  THU_TUC_HAI_QUAN: [
    'Checklist trước truyền',
    'Doanh nghiệp ưu tiên',
    'Giám sát hải quan',
    'Hồ sơ điện tử',
    'Hồ sơ nhập khẩu',
    'Hủy tờ khai',
    'Khai bổ sung',
    'Khai bổ sung container',
    'Khai bổ sung/hủy',
    'Kết thúc job',
    'Luật Hải quan - thời hạn',
    'Máy nhập nhiều chuyến',
    'Phân luồng',
    'Quy trình khai báo',
    'Thời hạn kiểm tra hải quan',
    'Xác định trước',
  ],
  HS_PHAN_LOAI: [
    'HS',
    'HS - bộ phận máy',
    'HS - căn cứ phân loại',
    'HS - hàng đa chức năng',
    'HS - mã tham khảo',
    'HS - máy tháo rời',
    'HS - quy trình phân loại',
    'HS & thông tin hàng',
    'Kiểm tra HS',
    'Xác định trước HS',
  ],
  THUE_TRI_GIA: [
    'Thuế',
    'Thuế - Gia công',
    'Thuế - Hoàn thuế',
    'Thuế - Khu phi thuế quan',
    'Thuế - SXXK',
    'Thuế - Thay đổi mục đích',
    'Thuế - Trị giá/giá chính thức',
    'Trị giá hải quan',
  ],
  XUAT_XU_CHUNG_TU: ['C/O', 'Chứng từ'],
  CHINH_SACH_CHUYEN_NGANH: [
    'Chính sách mặt hàng',
    'CNTT - laptop',
    'CNTT & viễn thông',
    'Dây cáp điện',
    'Đèn LED',
    'Hàng đã qua sử dụng',
    'Hóa chất',
    'In & xuất bản phẩm',
    'Kiểm tra chất lượng',
    'Lấy mẫu/phân tích',
    'Mật mã dân sự',
    'Máy móc đã qua sử dụng',
    'NĐ169 - giấy phép',
    'Nhãn hàng hóa',
    'Thép',
    'Thiết bị điện gia dụng',
    'Thiết bị vô tuyến',
    'Thuế & chuyên ngành',
    'Xuất bản phẩm',
  ],
  DNCX_XNK_TAI_CHO: [
    'DNCX',
    'DNCX - địa điểm làm thủ tục',
    'DNCX - khuôn thuê mượn',
    'DNCX - nội địa',
    'DNCX - phế liệu',
    'DNCX ↔ nội địa - thời hạn',
    'DNCX cơ bản',
    'DNCX nội địa',
    'Doanh nghiệp ưu tiên - XNK tại chỗ',
    'XNK tại chỗ',
    'XNK tại chỗ GC/SXXK',
  ],
  GIA_CONG_SXXK: [
    'BCQT',
    'CSSX',
    'GC/SXXK',
    'Gia công',
    'Gia công lại',
    'SXXK',
    'SXXK - phế liệu',
    'Xử lý NVL dư',
  ],
  LOAI_HINH_DAC_THU: [
    'Tái nhập sửa chữa/tái chế',
    'Tạm nhập bảo hành/sửa chữa',
    'Thay đổi mục đích',
    'Thay đổi mục đích sử dụng',
    'Tiêu hủy',
  ],
  PHAP_LY_TUAN_THU: [
    'Chuỗi văn bản',
    'Luật Hải quan - xác định trước',
    'Lưu vết hồ sơ',
    'Lưu vết pháp lý',
    'NĐ169 - khai sai thiếu thuế',
    'NĐ169 - nhận diện hành vi',
    'NĐ169 - sau thông quan',
    'NĐ169 - thay đổi mục đích',
    'NĐ169 - trốn thuế',
    'Nguồn pháp lý',
    'Nguồn tham khảo',
    'Rủi ro đa lớp',
    'Tra cứu pháp lý',
    'Tư duy tra cứu',
    'Tư vấn pháp lý',
    'Văn bản pháp luật',
    'Xử phạt VPHC',
  ],
  LOGISTICS_VAN_TAI: ['Điều vận', 'Incoterms & vận tải', 'Ops hiện trường', 'Vận tải'],
  VAN_HANH_CS_CHAT_LUONG: [
    'Case tổng hợp',
    'Chất lượng nghiệp vụ',
    'Công nợ',
    'CS-Kế toán',
    'Đối soát',
    'Escalation',
    'Giao tiếp khách hàng',
    'Giao tiếp sự cố',
    'Kiểm soát chất lượng CS1',
    'Phối hợp phòng ban',
    'Quản trị ngân hàng câu hỏi',
    'Sale-CS',
    'Vai trò CS2',
    'Xử lý phát sinh',
  ],
  AN_TOAN_KY_THUAT: [
    'Bảo hộ lao động',
    'Bình áp lực',
    'KTCN & bảo quản',
    'Pa lăng điện',
    'PPE/ATLĐ',
    'Thiết bị nâng/hạ',
  ],
};

export const CS_V2_TOPIC_CATEGORY = new Map<string, string>();
for (const [category, topics] of Object.entries(TOPICS_BY_CATEGORY)) {
  for (const topic of topics) CS_V2_TOPIC_CATEGORY.set(topic, category);
}
